apiVersion: v2
name: botexp2-xl
description: A Helm chart for Kubernetes for main chatbot service@exp2
type: application
version: 10.5.0
appVersion: 10.5.0
dependencies:
  - alias: botexp2
    name: eva-ml
    version: 1.1.3
    repository: oci://registry.lan:4567/charts/ml/app/chart
